### ISSUE TITLE
关于Search 搜索

### ISSUE THREAD

**Issue by sonong** [cnodejs/egg-cnode#102]
关于搜索alsotang大神坚持谷歌最好，但是国内翻墙不方便，能否加个 百度的 ,检测到被墙切换到百度。实现双站切换。当然如果练习node,最好做个本站搜索 如何分词什么的 。
exports.index = function (req, res, next) {
  var q = req.query.q;
  q = encodeURIComponent(q);
q1='+q+'&q2=&q3=&q4=&rn=10&lm=0&ct=0&ft=&q5=&q6=plmclub.org&tn=baiduadv');
  res.redirect('https://cnodejs/cse/search?q='+q+'&s=6701441402440425312&nsid=0');
  
};

**Comment by atian25** [comment]
服务端无法检测用户电脑是否被墙

**Comment by thonatos** [comment]
用 dropdown 同时支持 baidu/goolge 两种如何
