### ISSUE TITLE
授权github回调 500

### ISSUE THREAD

**Issue by finmily** [cnodejs/egg-cnode#103]
- `Internal Server Error, real status: 500`
- 回调链接：http://egg.cnodejs.org/passport/github/callback?code=3a571c6fb29698f72e92
重试一次好了。

**Comment by thonatos** [comment]
> https://cnodejs.org/topic/5aae1cc8f5dfc27d7ad98909

唔，刚也遇到，线上的版本已经是 `egg-cnode` 了，原测试站即将下线~

**Comment by jetiny** [comment]
@thonatos 依旧500啊

**Comment by jetiny** [comment]
回调链接: https://cnodejs.org/passport/github/callback?code=44d63ebfb10b1649a8f3

**Comment by thonatos** [comment]
@jetiny 

`http://egg.cnodejs.org` 稍后下线了，访问 `https://cnodejs.org` 就是 Egg 重构的版本了

**Comment by jetiny** [comment]
访问的就是这个地址, 又从新授权了一下还是不行 https://cnodejs.org/passport/github/callback?code=4a212971cb43a1fae23d
