### ISSUE TITLE
关于站内搜索的feature

### ISSUE THREAD

**Issue by lqs469** [cnodejs/egg-cnode#106]
cnode的egg公测帖子上有一个关于添加站内搜索的[反馈](http://egg.cnodejs.org/topic/5aae1cc8f5dfc27d7ad98909#5ab11978f5dfc27d7ad989e4)
大家看是否要支持一下这个需求?
我的想法是分三个主要搜索选项: 
- 谷歌
- 百度
- 本地数据
  - 搜索用户名
  - 搜索帖子名

里面可能涉及新页面设计, 风格上当然保持和原有一致.
大家觉得怎么样?

**Comment by JacksonTian** [comment]
我的建议是不要提供多个选项。

可以实现多种搜索，通过配置，指定一种。

**Comment by lqs469** [comment]
@JacksonTian 指定一种搜索方式给用户这样也不错, 那么支持一个站内搜索功能吧. 这个部分认领一下.

**Comment by web-L** [comment]
希望能提供多个选项搜索，或者只提供站内。

**Comment by JacksonTian** [comment]
站内搜索其实对 DB 压力会大。通过 Google 这种外部搜索方式，其实也是挺好的。

**Comment by JacksonTian** [comment]
不过我们可以实现。万一有人拿这个代码部署在内网呢，外部搜索就失效了。

**Comment by JacksonTian** [comment]
我们实现三种，Google、Baidu、本地。

通过配置，展现一种。

**Comment by lqs469** [comment]
#107 add search  mode: local, google, baidu.

**Comment by sonong** [comment]
@lqs469   使用本地搜索，输入中文的时候，搜不到内容
![default](https://user-images.githubusercontent.com/12076578/43044344-af2f46aa-8dd6-11e8-82e0-ff85556cc965.png)

**Comment by lqs469** [comment]
@sonong @JacksonTian 
已修复, 提PR: https://github.com/cnodejs/egg-cnode/pull/135

**Comment by sonong** [comment]
当时没注意测，我去测一下，感谢大神。
