### ISSUE TITLE
貌似代码跟线上在跑的cnode社区不是同一套

### ISSUE THREAD

**Issue by xjchenhao** [cnodejs/egg-cnode#109]
我拉的是主分支的代码哦

![image](https://user-images.githubusercontent.com/5373111/38122474-cbb22032-3407-11e8-8588-457c749c0fb9.png)
![image](https://user-images.githubusercontent.com/5373111/38122476-d370335e-3407-11e8-9824-9be699bb8a29.png)

**Comment by JacksonTian** [comment]
线上是 egg.cnodejs.org

**Comment by atian25** [comment]
最近的几个 PR 都有发布上线了？

**Comment by xjchenhao** [comment]
![image](https://user-images.githubusercontent.com/5373111/38122763-b5dc3fa2-3409-11e8-9410-d7971e354ecb.png)
嗯嗯，一致了。帖子内容没看仔细。。
