### ISSUE TITLE
API 部分的迁移计划？

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/egg-cnode#113]
RT

**Comment by YeungKC** [comment]
@JacksonTian 那么请问对于 API 迁移计划启动么？我个人得知这个项目之后想参与贡献一下…
本人是 Android 开发，在公司有机会接触 node.js 之后一直用，平时做外包等，不知道有没有机会参与进来…

**Comment by JacksonTian** [comment]
在开源社区，不要问有没有机会，主动干了就是机会。

**Comment by JacksonTian** [comment]
近段时间比较忙，没有重新搞起。如果有同学来帮忙迁移，可以帮忙继续 review 代码。

目前问题主要有2块：

- [ ] API
- [ ] passport

**Comment by YeungKC** [comment]
好的，我试试看，请问有本项目相关讨论组/群么？Telegram slack 这样？

**Comment by JacksonTian** [comment]
没有 = =。通过 issue 交流把

**Comment by sinchang** [comment]
不做分离的原因我觉得是：本次迁移重点还是在后端的代码，这样 view 层的代码是高度复用的。

**Comment by YeungKC** [comment]
@sinchang 
也是，可能我做 android 出身，习惯了这样…
因为是迁移老 api，只能先按老的来，现在主要问题是文件结构…emmmm，未来如果升级 V2 接口，当然更严格，或者采用 GraphQL？这都是后话了。

**Comment by atian25** [comment]
重构那个版本只聚焦于功能迁移，不做大的变更。
现在就可以做

**Comment by YeungKC** [comment]
@atian25 

你的意思是，egg-cnode 就是用 v2 更严格的 RESETfu api，老 v1 api 还在老服务器跑？



其实我奋战一天过后发现有点问题，因为之前完全漏掉了 API 的开发，所以中间件 passport 等各方面设计貌似要改动挺大…

而且我个人一直都是用 jwt 方式…所以对 passport 也不了解…也胜任不了。 T_T


但是如果你们开始改动之后（就是几种 API 开发了之后）…我想之后我还是有能力参与贡献的，也希望贡献…

**Comment by JacksonTian** [comment]
api 部分跟 passport 没啥直接的关系的。

**Comment by sinchang** [comment]
@TakWolf 我已经提交了一个例子，需要贡献代码的话可以参考下。

**Comment by YeungKC** [comment]
@sinchang 感恩，我下午看到还在想啥时候合进来，忙完就看到了~~

**Comment by TakWolf** [comment]
问一下：
1.目前API（v1）迁移目标是跟老版本兼容吗？目前线上环境 API（v1） 路由已经切换到迁移后的了吗？
2.由于历史原因，v1的接口很多地方设计不合理。是否有计划创建 v2 接口？

**Comment by JacksonTian** [comment]
本次仅做 v1 的迁移。v2 可以再行设计。
