### ISSUE TITLE
线上项目 egg-passport-github 总是提示redirect_uri_mismatch

### ISSUE THREAD

**Issue by noprom** [cnodejs/egg-cnode#122]
* **Node Version**:
8.9.4-alpine
* **Egg Version**:
^2.2.1
* **Plugin Name**:
egg-passport-github
* **Plugin Version**:
^1.0.0
* **Platform**:
ubuntu
* **Mini Showcase Repository**:
egg-passport-github作如下配置:
```
  config.passportGithub = {
    key: process.env.EGG_PASSPORT_GITHUB_CLIENT_ID,
    secret: process.env.EGG_PASSPORT_GITHUB_CLIENT_SECRET,
    callbackURL: 'https://eosdevs.io/passport/github/callback',
  };
```
这里保证`key`和`secret`没有问题, `callbackURL`在github中配置如下:
![image](https://user-images.githubusercontent.com/8455444/39663123-dec55130-509f-11e8-8334-0f8183aaae85.png)
即`https://eosdevs.io/passport/github/callback`,
但是线上项目`https://eosdevs.io`的使用github登陆总是提示`redirect_uri_mismatch`。
经过抓包发现,
![image](https://user-images.githubusercontent.com/8455444/39663143-5961e476-50a0-11e8-86b3-45c9820c4a6e.png)
期望能得到解答。

**Comment by thonatos** [comment]
问题重复，在那边回复吧。

- https://github.com/eggjs/egg/issues/2509
