### ISSUE TITLE
npm run assets 出现错误

### ISSUE THREAD

**Issue by unreal0** [cnodejs/egg-cnode#123]
环境:centos:7.2
> cnode@1.0.0 assets /root/egg-cnode
> loader app/view app/

Scaned. 3 asset(s) will be build.
Building... /public/editor.min.js
        processing... /public/libs/editor/editor.js ..build .. use 3692ms.
        processing... /public/libs/webuploader/webuploader.withoutimage.js ..build .. use 1519ms.
        processing... /public/libs/editor/ext.js ..build .. use 53ms.
✔ Done. Build time 5271 ms.
Building... /public/stylesheets/index.min.css
        processing... /public/libs/bootstrap/css/bootstrap.css ..build .. use 436ms.
        processing... /public/stylesheets/common.css ..build .. use 4ms.
        processing... /public/stylesheets/style.less ..build .. use 142ms.
        processing... /public/stylesheets/responsive.css ..build .. use 36ms.
        processing... /public/stylesheets/jquery.atwho.css ..build .. use 2ms.
        processing... /public/libs/editor/editor.css ..build .. use 45ms.
        processing... /public/libs/webuploader/webuploader.css ..build .. use 1ms.
        processing... /public/libs/code-prettify/prettify.css ..build .. use 15ms.
        processing... /public/libs/font-awesome/css/font-awesome.css ..build .. use 25ms.
✔ Done. Build time 709 ms.
Building... /public/index.min.js
        processing... /public/libs/jquery-2.1.0.js ..build .. use 1827ms.
        processing... /public/libs/lodash.compat.js ..build .. use 1291ms.
        processing... /public/libs/jquery-ujs.js ..build .. use 82ms.
        processing... /public/libs/bootstrap/js/bootstrap.js ..build .. use 339ms.
        processing... /public/libs/jquery.caret.js ..build .. use 83ms.
        processing... /public/libs/jquery.atwho.js ..build .. use 202ms.
        processing... /public/libs/markdownit.js ..build .. use 1057ms.
        processing... /public/libs/code-prettify/prettify.js ..build .. use 159ms.
        processing... /public/libs/qrcode.js ..build .. use 430ms.
        processing... /public/javascripts/main.js ..build .. use 11ms.
        processing... /public/javascripts/responsive.js ..build .. use 23ms.
✔ Done. Build time 5516 ms.
 🏁  Compile static assets done. Build time 11506 ms.
assets.json is here:  /root/egg-cnode/app/assets.json
fs.js:124
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.writeFile (fs.js:1244:14)
    at Object.<anonymous> (/root/egg-cnode/node_modules/loader-builder/bin/builder:49:4)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cnode@1.0.0 assets: `loader app/view app/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cnode@1.0.0 assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-06T01_40_37_539Z-debug.log

**Comment by JacksonTian** [comment]
node 什么版本

**Comment by unreal0** [comment]
node 10.0.0

**Comment by JacksonTian** [comment]
请重新安装依赖。
