### ISSUE TITLE
[TODO] API 迁移

### ISSUE THREAD

**Issue by sinchang** [cnodejs/egg-cnode#125]
Todo list: 
- [x] 用户
- [x] 主题
- [x] 主题收藏
- [x] 评论
- [x] 消息通知

根据老 API 文档，划分了以上几大模块，欢迎认领贡献。👏

Links:
- [cnode api](https://cnodejs.org/api)

**Comment by YeungKC** [comment]
主题已经完成
希望也认领其他

**Comment by XGHeaven** [comment]
那我先认领一下评论部分

**Comment by sinchang** [comment]
@YeungKC 还有一个你在做吗？

**Comment by YeungKC** [comment]
@sinchang sorry…我最近工作有点忙，所以暂时不能参与了。
