### ISSUE TITLE
npm run assets err log

### ISSUE THREAD

**Issue by sonong** [cnodejs/egg-cnode#129]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'assets' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'preassets', 'assets', 'postassets' ]
5 info lifecycle bbs@1.0.0~preassets: bbs@1.0.0
6 info lifecycle bbs@1.0.0~assets: bbs@1.0.0
7 verbose lifecycle bbs@1.0.0~assets: unsafe-perm in lifecycle true
8 verbose lifecycle bbs@1.0.0~assets: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Github\bbs\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Users\sonong\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\sonong\AppData\Local\atom\bin;C:\Users\sonong\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\Users\sonong\AppData\Roaming\npm
9 verbose lifecycle bbs@1.0.0~assets: CWD: D:\Github\bbs
10 silly lifecycle bbs@1.0.0~assets: Args: [ '/d /s /c', 'loader app/view app/' ]
11 silly lifecycle bbs@1.0.0~assets: Returned: code: 1  signal: null
12 info lifecycle bbs@1.0.0~assets: Failed to exec assets script
13 verbose stack Error: bbs@1.0.0 assets: `loader app/view app/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid bbs@1.0.0
15 verbose cwd D:\Github\bbs
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "assets"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error bbs@1.0.0 assets: `loader app/view app/`
22 error Exit status 1
23 error Failed at the bbs@1.0.0 assets script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
![menu saveimg savepath20180511161956](https://user-images.githubusercontent.com/12076578/39914309-3b4fe7f8-5537-11e8-8632-a5351e22f5a5.jpg)

**Comment by JacksonTian** [comment]
路径不对吧。

**Comment by sonong** [comment]
@JacksonTian  朴大 我是部署在了windows环境 ，源码路径应该没问题的 您指的是哪个路径有问题？

**Comment by jiayisheji** [comment]
@sonong 需要把css里面的路径改了，比如`../images/search.png` 改成`public/images/search.png`

**Comment by atange** [comment]
> @sonong 需要把css里面的路径改了，比如`../images/search.png` 改成`public/images/search.png`
这样写路径并不是一样的吗，有什么区别？

**Comment by atange** [comment]
@jiayisheji   多谢大侠相助，终于理解了。历史好几个月，还好是学习项目。
直接运行会报错，这个问题在egg-node有人提issues

z90d4zb w t t26e_2 l

主要是静态资源css引用的背景图片和字体地址有错误，需要修改哪些文件：

错误信息：

no such file or directory, open 'E:\github\nest-cnode\E:\public\img\glyphicons-halflings.png'

谁引用了它 Error! File:/public/libs/bootstrap/css/bootstrap.css

/public/libs/bootstrap/css/bootstrap.css

...
[class^="icon-"],
[class*=" icon-"] {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin-top: 1px;
    *margin-right: .3em;
    line-height: 14px;
    vertical-align: text-top;
    background-image: url("/public/libs/bootstrap/img/glyphicons-halflings.png");
    background-position: 14px 14px;
    background-repeat: no-repeat;
}
...

.icon-white,
.nav-pills > .active > a > [class^="icon-"],
.nav-pills > .active > a > [class*=" icon-"],
.nav-list > .active > a > [class^="icon-"],
.nav-list > .active > a > [class*=" icon-"],
.navbar-inverse .nav > .active > a > [class^="icon-"],
.navbar-inverse .nav > .active > a > [class*=" icon-"],
.dropdown-menu > li > a:hover > [class^="icon-"],
.dropdown-menu > li > a:focus > [class^="icon-"],
.dropdown-menu > li > a:hover > [class*=" icon-"],
.dropdown-menu > li > a:focus > [class*=" icon-"],
.dropdown-menu > .active > a > [class^="icon-"],
.dropdown-menu > .active > a > [class*=" icon-"],
.dropdown-submenu:hover > a > [class^="icon-"],
.dropdown-submenu:focus > a > [class^="icon-"],
.dropdown-submenu:hover > a > [class*=" icon-"],
.dropdown-submenu:focus > a > [class*=" icon-"] {
    background-image: url("/public/libs/bootstrap/img/glyphicons-halflings-white.png");
}
...
大约2296和2320行位置，你可以用查找搜索glyphicons-halflings.png，默认是background-image: url("../img/glyphicons-halflings.png");, 替换为上面写法。

/public/stylesheets/style.less

...
.navbar .search-query {
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  background: #888 url('/public/images/search.png') no-repeat 4px 4px;
  padding: 3px 5px 3px 22px;
  color: #666;
  border: 0px;
  margin-top: 2px;

  &:hover {
    background-color: white;
  }
  transition: all 0.5s;

  &:focus, &.focused {
    background-color: white;
  }
}
...
大约850行位置

简单解释就是换成相对于根目录的路径，后面错误就类似。

45 7el q a5ph tf g84r 0

打包成功以后会输出一个assets.json在根目录。assets指的就是这个json文件，后面我们会讲如果把它们关联起来。
