### ISSUE TITLE
email 迁移

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/egg-cnode#14]

**Comment by thonatos** [comment]
这里用 nodemailer 还是 dm 服务呢

**Comment by JacksonTian** [comment]
还是用 nodemailer 。不过接口要迁移为基于 Promises/Async Functions。

**Comment by sinchang** [comment]
I will do this issue

**Comment by thonatos** [comment]
@sinchang `egg-nodemailer` 如果有问题的话重新封装一个吧，可以考虑提交到 [eggjs-community](https://github.com/eggjs-community)

**Comment by JacksonTian** [comment]
Thanks @sinchang
