### ISSUE TITLE
收不到发送的邮件

### ISSUE THREAD

**Issue by thxallvu** [cnodejs/egg-cnode#142]
阿里云ecs ，安全组开放了465，用的qq 163 企业邮箱都试了，都提示发送成功，但实际收不到注册邮件。求解决方案~~

**Comment by thxallvu** [comment]
后来自己写了一个测试的程序 用的也是nodemailer 可以发送成功，应该不是服务器设置的问题，邮件配置因该也没有问题，不知道为什么收不到邮件。。。

**Comment by atange** [comment]
邮件收不到是哪里的问题啊？25  465都尝试了
