### ISSUE TITLE
[egg:core:ready_timeout] 10 seconds later redis.js was still unable to finish.

### ISSUE THREAD

**Issue by JakeWoki** [cnodejs/egg-cnode#149]
WARN 17992 [egg:core:ready_timeout] 10 seconds later \egg-cnode\node_modules\egg-redis\lib\redis.js:48:7 was still unable to finish.

小白求助这个啥？redis连接超时？要怎么处理？搜索了没有对应的问题

**Comment by atian25** [comment]
地址写错了吧，或者防火墙，导致连接 redis 出错。

**Comment by JakeWoki** [comment]
是没启动redis...
