### ISSUE TITLE
根目录的app.js一启动是调用了吗？怎么用的？

### ISSUE THREAD

**Issue by JakeWoki** [cnodejs/egg-cnode#150]
看了[koa2-note](https://github.com/chenshenhai/koa2-note)感觉挺清晰的，再看egg文档一脸懵逼...好像没提到app.js这个结构。还有init.d/mongo下的init.js和bin下的generate_access_token.js
没学到ejs都不知道是怎么调用了接口的

**Comment by atian25** [comment]
先去把 egg 基础文档看看吧

![image](https://user-images.githubusercontent.com/227713/50337683-dd4d6100-054c-11e9-9e81-eb5a2b06b769.png)
