### ISSUE TITLE
论坛无法访问了么?

### ISSUE THREAD

**Issue by shenqidebaozi** [cnodejs/egg-cnode#165]
如题
![image](https://user-images.githubusercontent.com/35397691/72323214-1f5ebd00-36e3-11ea-98bd-4b3c5b59db89.png)

**Comment by duziten** [comment]
不知道为啥，挂了好久了，没人处理

**Comment by shay-an** [comment]
还没人处理啊

**Comment by atian25** [comment]
据我了解：因为某些帖子违反规定，域名解析被运营商干掉了。还在沟通处理中。

**Comment by chunjiu** [comment]
这搜索某些内容的技术很给力啊

**Comment by tomatoFQ** [comment]
不考虑放一波IP访问吗？

**Comment by kdming** [comment]
挂掉快一个月了

**Comment by jigsaw-china** [comment]
nodejs挺住！疫情开始感觉越来越冷淡了

**Comment by yuu2lee4** [comment]
挂掉快两个月了

**Comment by atian25** [comment]
快了，快了，已经提交审核了，等审批中，短则一天，长则一个月。。。看老爷们的审批速度。

**Comment by shenqidebaozi** [comment]
@atian25 域名备案吗

**Comment by atian25** [comment]
嗯

**Comment by LiuWeiMr** [comment]
能用了及时评论回复下呀

**Comment by atian25** [comment]
https://cnodejs.org/topic/5fdb44d70f99cb37f45e3410

已经赶在 2021 年前恢复了
