### ISSUE TITLE
论坛又无法访问了吗

### ISSUE THREAD

**Issue by ikomom** [cnodejs/egg-cnode#194]
![image](https://github.com/cnodejs/egg-cnode/assets/25498555/f5eee7cb-50aa-4fae-8a00-2e72bc328320)

**Comment by fengmk2** [comment]
嗯，已经联系管理员处理中

**Comment by fengmk2** [comment]
已恢复 
![image](https://github.com/cnodejs/egg-cnode/assets/156269/613f0a2d-8b1f-458a-8255-df2bf51b7e9d)
