### ISSUE TITLE
Controller：topic 相关

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/egg-cnode#20]

**Comment by xiaomuzhu** [comment]
我申请认领重构topic相关内容😄

**Comment by JacksonTian** [comment]
Thanks @xiaomuzhu 1-3天内能完成吗？

**Comment by xiaomuzhu** [comment]
@JacksonTian 可以的,不过是不是跟 https://github.com/cnodejs/egg-cnode/issues/17 重复了?

**Comment by JacksonTian** [comment]
@xiaomuzhu 有进展吗？

**Comment by xiaomuzhu** [comment]
@JacksonTian 目前还差一个上传功能和测试部分.

有两个问题
1. 老版本的upload功能分成了本地储存和七牛云储存,我们的逻辑是优先七牛云储存对吗?
2.测试覆盖率有硬性要求吗?

**Comment by atian25** [comment]
覆盖率我们期望是 100%

**Comment by JacksonTian** [comment]
1. 都要兼顾。
2. 覆盖率可以分阶段达成吧。70%、90%、100%
