### ISSUE TITLE
Controller：reply 相关接口

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/egg-cnode#21]

**Comment by GeaJiang** [comment]
我申请认领重构reply相关内容

**Comment by JacksonTian** [comment]
Thanks @GeaJiang 预计1-3天内能完成吗。

**Comment by GeaJiang** [comment]
@JacksonTian 3天可以完成，关于上传文件如果我有些不清楚的地方可以问你吗？我看上传是用busboy，我之前只用过express的multer

**Comment by atian25** [comment]
@GeaJiang 看 egg 的上传文档和示例

**Comment by GeaJiang** [comment]
@atian25 好的

**Comment by JacksonTian** [comment]
@GeaJiang 有进展吗

**Comment by GeaJiang** [comment]
@JacksonTian 有的，今晚除了上传图片，都可以完成的

**Comment by JacksonTian** [comment]
文件上传另外 PR。
