### ISSUE TITLE
[Feature request] Migrate to es6 api both code and test using babel-node

### ISSUE THREAD

**Issue by gengjiawen** [cnodejs/egg-cnode#24]

**Comment by atian25** [comment]
why?

**Comment by gengjiawen** [comment]
mainly import export

**Comment by atian25** [comment]
I don't think it's necessary.

and we are planning to refactor to typescript once tegg is ready

**Comment by gengjiawen** [comment]
will this project use ts too ?

**Comment by atian25** [comment]
when tegg is ready, then I will start a new refactor plan.

**Comment by gengjiawen** [comment]
thanks.

**Comment by JacksonTian** [comment]
When Node ready, we change to import/export directly. No need babel.
