### ISSUE TITLE
本地开发说明

### ISSUE THREAD

**Issue by atian25** [cnodejs/egg-cnode#28]
- [ ] 提供 dockerfile 用于本地 test-local 测试
- [ ] 修改 README 补充本地开发调试指南

**Comment by thonatos** [comment]
dockerfile 以及 docker-compose 一键拉起类正式环境（#38）

**Comment by thonatos** [comment]
@atian25 ，在这边讨论，Docker 支持：

### 正式环境

- dockerfile 用于构建 egg-cnode 镜像（可以加到 docker hub 自动构建）
- docker-compose.yml 启动一个基本和正式环境完全一致的服务（egg-cnode/redis/mongo)

### 开发环境

这边 docker 有两种用法：
- docker-compose-dev.yml 只启动 redis/mongo 等数据库及相关服务
- docker-compose-dev.yml 启动测试环境
  - docker 构建是分阶段的，package.json 变化才会重新装 node_modules
  - 仅 copy 代码消耗可以忽略不计了
  - 这样可以很好的解决 “代码在我这里可以跑，在其他人那边就不行了” 的问题

**Comment by atian25** [comment]
我现在的需求很简单，要提供开发期支持，不然本地 egg-bin test 的时候，要自己启动 redis 和 mongo

部署这个暂时不关心

**Comment by thonatos** [comment]
好的，那我新建一个 compose file 用于启动 mongo/redis

**Comment by thonatos** [comment]
done.
