### ISSUE TITLE
Unit test for service

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/egg-cnode#35]
- [x] user
- [x] topic
- [x] reply
- [x] message
- [x] topic_collect
- [x] at

**Comment by JacksonTian** [comment]
参考 https://github.com/cnodejs/egg-cnode/blob/master/test/app/service/user.test.js

**Comment by sinchang** [comment]
hi @JacksonTian  希望参与开发 service topic unit test

**Comment by JacksonTian** [comment]
@sinchang 好的。

**Comment by JacksonTian** [comment]
还有两个 service

**Comment by sinchang** [comment]
今天我再写下 message 和 at。

**Comment by JacksonTian** [comment]
@sinchang 辛苦～

**Comment by JacksonTian** [comment]
目前还有 message。
