### ISSUE TITLE
EJS API 变更

### ISSUE THREAD

**Issue by thonatos** [cnodejs/egg-cnode#7]
## 列表

- partial => incluede

## 链接
- http://ejs.co/

**Comment by atian25** [comment]
后面我想重构为 nunjucks 的

**Comment by JacksonTian** [comment]
nunjucks 新版本上线之后再考虑重构吧。目前主要考虑架构迁移完成，再优化局部。除非绕不过去需要选新的技术的，否则尽量只做升级。

**Comment by atian25** [comment]
是的
