### ISSUE TITLE
为什么代码里面用到的try catch那么少呢

### ISSUE THREAD

**Issue by dengnan123** [cnodejs/egg-cnode#74]
我看controller 里面就在上传七牛云里面用到了 try catch

**Comment by atian25** [comment]
为什么要那么多 catch ?

**Comment by fengmk2** [comment]
如果错误你不处理，不需要 try catch

**Comment by JacksonTian** [comment]
不写那么多 try catch  是因为没有那么多精细化的需求，只要统一让框架兜底的 try catch 来处理就可以了。
