### ISSUE TITLE
关于 loader 的疑问

### ISSUE THREAD

**Issue by nanzm** [cnodejs/egg-cnode#93]
为什么clone下项目，运行npm run start 的时候 ，页面 js 和 css 没有加载进来，是我缺少了什么步骤吗 （npm run dev 没问题 页面是正常的  ，已经运行了 `npm run assets  `  同时生成了 assets.json  ，代码方面只修改了 `redis mongo` 配置 ）

**Comment by nanzm** [comment]
已经运行了 `npm run assets  `  同时生成了 assets.json  ，代码方面只修改了 `redis mongo` 配置

**Comment by nanzm** [comment]
发现了问题  是这个 mini_assets  没有配置

**Comment by atian25** [comment]
欢迎 PR

**Comment by thonatos** [comment]
唔，#95 里补充了~
