### ISSUE TITLE
egg重构后cnode用github登录时,报错500

### ISSUE THREAD

**Issue by XposedHelper** [cnodejs/egg-cnode#94]
浏览器中地址
http://egg.cnodejs.org/passport/github/callback?code=8aaae50ef8bb8c167f6e 
返回错误提示:
Internal Server Error, real status: 500

**Comment by thonatos** [comment]
使用你提供的code显示过期，使用本地测试未复现问题。

```
TokenError in /passport/github/callback?code=8aaae50ef8bb8c167f6e
The code passed is incorrect or expired. (code: bad_verification_code)
```

先关闭了，如果依然有问题，欢迎再次提交 issue.

**Comment by JacksonTian** [comment]
我们应该跳转到一个错误页面 = =
