### ISSUE TITLE
增加 Egg 驱动的文案

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/egg-cnode#98]
在 CNode 中，增加一些 Egg.js 相关的文案。

- [x] 底部源码地址
- [ ] Egg.js 友情链接

**Comment by iyuq** [comment]
@JacksonTian 底部源码地址是要加上 `Egg.js` 的源码地址吗？

**Comment by atian25** [comment]
加官网的吧 https://eggjs.org/  图片我找 @子溯 导下

**Comment by iyuq** [comment]
恩，我找了张 `github` 上的，和上面几个友情链接不太协调

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/37748046-1e257888-2dbd-11e8-96a4-eadc9f434bdb.png)

**Comment by atian25** [comment]
README 的顶部也可以改改，powered by Egg 啥的

**Comment by thonatos** [comment]
@atian25 可以搞一个 Egg 的 Badge 链接，还可以做统计~

**Comment by atian25** [comment]
不知道咋搞

**Comment by thonatos** [comment]
https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by atian25** [comment]
赞

**Comment by JacksonTian** [comment]
谁加下右边的友情链接。

**Comment by thonatos** [comment]
@atian25 logo 不搭，有其他 logo 么

**Comment by atian25** [comment]
我看现在下面那几个也没搭啊

**Comment by thonatos** [comment]
done.

**Comment by thonatos** [comment]
@JacksonTian 

朴老师，没问题的话可以关 issue 了
